# Generated by Django 2.2.6 on 2019-12-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlesGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('date', models.TextField()),
                ('page', models.IntegerField()),
                ('position', models.IntegerField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('publisher', models.TextField()),
                ('pages', models.FloatField()),
                ('publication_date', models.CharField(max_length=100)),
                ('sales_rank', models.FloatField()),
                ('image', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=100)),
            ],
        ),
    ]
