# Generated by Django 2.2.6 on 2019-12-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_titlesgeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrimTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('publisher', models.TextField()),
                ('marketingservices', models.TextField()),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
